#!/usr/bin/env node
import path from "node:path";
import { fileURLToPath } from "node:url";

import { parseActSearchRows } from "./lib/html.mjs";
import { fetchText, sleep } from "./lib/http.mjs";
import { readDataFile, writeDataFile } from "./lib/lino.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SEARCH_URL = "https://www.indiacode.nic.in/handle/123456789/1362/simple-search";

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const output = path.resolve(ROOT, args.output ?? "data/laws.discovered.lino");
  const rpp = Number(args.rpp ?? 100);
  const limit = Number(args.limit ?? 0);
  const delayMs = Number(args["delay-ms"] ?? 1100);
  const seedPath = path.resolve(ROOT, args.seed ?? "data/laws.seed.lino");
  const seed = await readDataFile(seedPath);
  const laws = [];
  let start = 0;

  while (true) {
    const url = new URL(SEARCH_URL);
    url.searchParams.set("query", "");
    url.searchParams.set("sort_by", "dc.date.enactment_dt");
    url.searchParams.set("order", "desc");
    url.searchParams.set("rpp", String(rpp));
    url.searchParams.set("etal", "0");
    url.searchParams.set("start", String(start));

    const html = await fetchText(url.toString());
    const pageRows = parseActSearchRows(html);
    for (const row of pageRows) {
      if (!laws.some((law) => law.handle === row.handle)) {
        laws.push(row);
      }
      if (limit > 0 && laws.length >= limit) {
        break;
      }
    }

    if (pageRows.length === 0 || (limit > 0 && laws.length >= limit)) {
      break;
    }

    start += rpp;
    await sleep(delayMs);
  }

  const manifest = {
    generatedFrom: ["https://www.indiacode.nic.in/handle/123456789/1362/simple-search"],
    lastVerified: new Date().toISOString().slice(0, 10),
    notes: [
      "Generated by scripts/discover-laws.mjs.",
      "Seed laws are preserved when the live listing is unavailable or intentionally limited."
    ],
    laws: laws.length ? laws : seed.laws
  };

  await writeDataFile(output, manifest);
  console.log(`Discovered ${manifest.laws.length} laws -> ${path.relative(ROOT, output)}`);
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith("--")) {
      continue;
    }
    const [key, inlineValue] = arg.slice(2).split("=");
    if (inlineValue !== undefined) {
      args[key] = inlineValue;
    } else if (argv[index + 1] && !argv[index + 1].startsWith("--")) {
      args[key] = argv[index + 1];
      index += 1;
    } else {
      args[key] = true;
    }
  }
  return args;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
